variables:
  BASENAME: go-ipfs

stages:
  - check
  - build
  - mirror

check:
  image: yrzr/docker-arm32v7:stable-git
  stage: check
  tags:
    - armhf
    - docker
  only:
    - branches
  script:
    - apk add --no-cache openssh-client bash curl coreutils
    - git config --global user.email $GIT_USER_EMAIL && git config --global user.name $GIT_USER_NAME
    - mkdir -p ~/.ssh && echo "$GITLAB_SSH_PRIV_KEY" > ~/.ssh/id_rsa && ssh-keyscan -H git.yrzr.ocry.com > ~/.ssh/known_hosts && chmod -R 0600 ~/.ssh/
    - git fetch --tags && ./check-version.sh && ./create-tags.sh
    - git push --tags https://${GITLAB_USER_LOGIN}:${PERSONAL_ACCESS_TOKEN}@git.yrzr.ocry.com/docker/go-ipfs-armhf.git

.build_stage: &build_stage
  stage: build
  only:
    - tags
  script:
    # setup dockerd
    - /usr/local/bin/dockerd-entrypoint.sh &
    - apk add --no-cache bash coreutils
    - docker info || sleep 5 && docker info
    # fetch dockerfile
    - git clone -b ${CI_COMMIT_TAG} --depth=1 https://github.com/ipfs/go-ipfs.git
    - cd ./go-ipfs
    # build
    - sed -i "s/golang\:/${ARMVER}\/golang\:/" ./Dockerfile && sed -i "s/busybox\:/${ARMVER}\/busybox\:/" ./Dockerfile && sed -i 's/x86_64-linux-gnu/arm-linux-gnueabihf/' ./Dockerfile && sed -i "s/VERSION\/tini/VERSION\/tini-${ARCH_NAME}/" ./Dockerfile
    - docker build -t ${DOCKER_NS}/${BASENAME}-${ARMVER}:${CI_COMMIT_TAG} -f ./Dockerfile ./
    # latest tag
    - cd ../ && git fetch --tags && ./latest-tag.sh
    # docker push
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD 
    - docker images && docker push ${DOCKER_NS}/${BASENAME}-${ARMVER}

build-armv7:
  <<: *build_stage
  image: yrzr/docker-arm32v7:stable-dind-git
  tags:
    - armhf
    - docker
  variables:
    ARCH_NAME: armhf
    ARMVER: arm32v7

build-armv8:
  <<: *build_stage
  image: arm64v8/docker:stable-dind-git
  tags:
    - aarch64
    - docker
  variables:
    ARCH_NAME: arm64
    ARMVER: arm64v8

mirror:
  image: yrzr/docker-arm32v7:stable-git
  stage: mirror
  only:
    - master
  except:
    - schedules
  script:
    - mkdir -p ~/.ssh
    - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
    - ssh-keyscan -H github.com > ~/.ssh/known_hosts
    - chmod -R 0600 ~/.ssh/
    - git remote | grep github || git remote add github git@github.com:yrzr/go-ipfs-armhf.git
    - git fetch github
    - git push github "$CI_BUILD_REF_NAME" -f
